version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        restart: unless-stopped
        tty: true
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: Backoffice
            MYSQL_USER: luan
            MYSQL_ROOT: root
            MYSQL_PASSWORD: luan
            MYSQL_ROOT_PASSWORD: 
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306